services:
  hephaestus-api:
    build: ./server
    image: hephaestus-api
    container_name: hephaestus-api
    ports:
      - "3005:3005"
    volumes:
      - ./data:/app/data
      - ./dashboard:/app/dashboard
      - ./server/src:/app/src
    environment:
      - INTERESTS_PATH=/app/data/interests.json
      - FEEDS_PATH=/app/data/feed_config.json
    env_file:
      - ./server/.env
    restart: always

networks:
  default:
    name: aegis-network
    external: false
