import React, { useState } from 'react';
import { motion, AnimatePresence, Reorder } from 'framer-motion';
import { 
  Save, 
  RotateCcw, 
  Plus, 
  Settings2, 
  Globe, 
  Hash, 
  Network, 
  Cpu, 
  Edit3,
  Trash2,
  GripVertical,
  X,
  Sparkles
} from 'lucide-react';
import { GlassPanel } from './GlassPanel';
import { KnowledgeGraph } from './KnowledgeGraph';
import { SkillRegistry } from './SkillRegistry';
import { nexusApi } from '../api/nexusApi';
import type { NexusSettings, Skill, InterestCategory } from '../types';
import type { DialogType } from './CustomDialog';

interface UnifiedEditorProps {
  currentSettings: NexusSettings;
  onSave: (newSettings: NexusSettings) => Promise<void>;
  alert: (title: string, message: string, type?: DialogType) => Promise<void>;
  confirm: (title: string, message: string) => Promise<boolean>;
  prompt: (title: string, message: string, defaultValue?: string, placeholder?: string) => Promise<string | null>;
}

type Tab = 'editor' | 'graph' | 'skills';

const DEFAULT_SKILLS: Skill[] = [
  { id: 'rss-fetch', name: 'RSS Fetcher', description: 'Retrieves raw signals from configured sources with deduplication.', agent: 'Discovery', type: 'tool', enabled: true },
  { id: 'semantic-filter', name: 'Semantic Filter', description: 'Analyzes article relevance using Gemini 3.1 embeddings.', agent: 'Architect', type: 'logic', enabled: true },
  { id: 'entity-extract', name: 'Entity Extraction', description: 'Identifies brands and keywords within text content.', agent: 'Curator', type: 'tool', enabled: true },
  { id: 'version-sync', name: 'Version Control Sync', description: 'Safely commits interest changes to the persistent layer.', agent: 'Archivist', type: 'action', enabled: true },
  { id: 'site-discovery', name: 'Source Discovery', description: 'Finds new authoritative RSS feeds based on current interests.', agent: 'Discovery', type: 'action', enabled: true },
  { id: 'reasoning-gen', name: 'Reasoning Engine', description: 'Generates user-friendly explanations for curated content.', agent: 'Curator', type: 'logic', enabled: true },
];

export const UnifiedEditor: React.FC<UnifiedEditorProps> = ({ 
  currentSettings, 
  onSave,
  alert: customAlert,
  confirm: customConfirm,
  prompt: customPrompt
}) => {
  const [draft, setDraft] = useState<NexusSettings>(currentSettings);
  const [activeTab, setActiveTab] = useState<Tab>('editor');
  const [isSaving, setIsSaving] = useState(false);
  const [isSuggesting, setIsSuggesting] = useState(false);
  const [isSuggestingBrands, setIsSuggestingBrands] = useState(false);
  const [isSuggestingKeywords, setIsSuggestingKeywords] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<string | null>(
    Object.keys(currentSettings.interests.categories)[0] || null
  );

  const isDirty = JSON.stringify(draft) !== JSON.stringify(currentSettings);
  const categoryKeys = Object.keys(draft.interests.categories);

  const handleReorderCategories = (newOrder: string[]) => {
    setDraft(prev => {
      const newCategories: Record<string, InterestCategory> = {};
      newOrder.forEach(key => {
        newCategories[key] = prev.interests.categories[key];
      });
      return {
        ...prev,
        interests: {
          ...prev.interests,
          categories: newCategories
        }
      };
    });
  };

  const handleAddCategory = async () => {
    const name = await customPrompt('New Category', 'Enter a name for the new intelligence category:', '', 'e.g. Quantum Computing');
    if (!name) return;
    if (draft.interests.categories[name]) {
      await customAlert('Category Exists', 'This category already exists in your configuration.', 'warning');
      return;
    }

    setIsSuggesting(true);
    try {
      // Gemini API を呼び出して提案を取得
      const suggestions = await nexusApi.suggestCategory(name);
      
      setDraft(prev => ({
        ...prev,
        interests: {
          ...prev.interests,
          categories: {
            ...prev.interests.categories,
            [name]: {
              emoji: suggestions.emoji || '🆕',
              brands: suggestions.brands || [],
              keywords: suggestions.keywords || [],
              score: 5,
              reason: suggestions.reason || 'Automatically generated by Gemini.'
            }
          }
        }
      }));
      setSelectedCategory(name);
      await customAlert('Suggestions Ready', `Gemini has suggested 5 brands and 5 keywords for "${name}".`, 'success');
    } catch (err) {
      console.error('Failed to get suggestions:', err);
      // 提案に失敗しても空のカテゴリを追加
      setDraft(prev => ({
        ...prev,
        interests: {
          ...prev.interests,
          categories: {
            ...prev.interests.categories,
            [name]: {
              emoji: '🆕',
              brands: [],
              keywords: [],
              score: 5,
              reason: 'Manually added category.'
            }
          }
        }
      }));
      setSelectedCategory(name);
    } finally {
      setIsSuggesting(false);
    }
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      await onSave(draft);
      await customAlert('Success', 'Configuration saved successfully!', 'success');
    } catch (error: any) {
      console.error('Save failed:', error);
      const message = error.response?.data?.details || error.message || 'Unknown error';
      
      if (message.includes('CONFLICT')) {
        const shouldReload = await customConfirm('Sync Conflict', 'The configuration on the server is newer. Would you like to discard your changes and reload the latest version?');
        if (shouldReload) {
          window.location.reload();
        }
      } else {
        await customAlert('Save Failed', `Failed to save configuration: ${message}`, 'error');
      }
    } finally {
      setIsSaving(false);
    }
  };

  const handleReset = () => {
    setDraft(currentSettings);
  };

  const handleKeywordToggle = (category: string, keyword: string, enabled: boolean) => {
    setDraft(prev => {
      const newCategories = { ...prev.interests.categories };
      const cat = { ...newCategories[category] };
      if (enabled) {
        if (!cat.keywords.includes(keyword)) cat.keywords = [...cat.keywords, keyword];
      } else {
        cat.keywords = cat.keywords.filter(k => k !== keyword);
      }
      newCategories[category] = cat;
      return { ...prev, interests: { ...prev.interests, categories: newCategories } };
    });
  };

  const handleBrandToggle = (category: string, brand: string, enabled: boolean) => {
    setDraft(prev => {
      const newCategories = { ...prev.interests.categories };
      const cat = { ...newCategories[category] };
      if (enabled) {
        if (!cat.brands.includes(brand)) cat.brands = [...cat.brands, brand];
      } else {
        cat.brands = cat.brands.filter(b => b !== brand);
      }
      newCategories[category] = cat;
      return { ...prev, interests: { ...prev.interests, categories: newCategories } };
    });
  };

  const handleToggleSkill = (skillId: string) => {
    setDraft(prev => {
      const currentSkills = prev.interests.skills || DEFAULT_SKILLS;
      const newSkills = currentSkills.map(s => 
        s.id === skillId ? { ...s, enabled: !s.enabled } : s
      );
      return { ...prev, interests: { ...prev.interests, skills: newSkills } };
    });
  };

  const handleDeleteCategory = async (catName: string) => {
    const confirmed = await customConfirm('Delete Category', `Are you sure you want to permanently delete the category "${catName}"? All associated brands and keywords will be removed.`);
    if (!confirmed) return;
    
    setDraft(prev => {
      const newCategories = { ...prev.interests.categories };
      delete newCategories[catName];
      return { ...prev, interests: { ...prev.interests, categories: newCategories } };
    });
    if (selectedCategory === catName) {
      const keys = Object.keys(draft.interests.categories);
      const remaining = keys.filter(k => k !== catName);
      setSelectedCategory(remaining[0] || null);
    }
  };

  const handleUpdateCategory = (name: string, field: 'brands' | 'keywords', values: string[]) => {
    setDraft(prev => {
      const newCategories = { ...prev.interests.categories };
      newCategories[name] = { ...newCategories[name], [field]: values };
      return { ...prev, interests: { ...prev.interests, categories: newCategories } };
    });
  };

  const handleAISuggest = async (field: 'brands' | 'keywords') => {
    if (!selectedCategory) return;
    
    if (field === 'brands') setIsSuggestingBrands(true);
    else setIsSuggestingKeywords(true);

    try {
      const suggestions = await nexusApi.suggestCategory(selectedCategory);
      const newItems = suggestions[field] || [];
      
      setDraft(prev => {
        const currentItems = prev.interests.categories[selectedCategory][field];
        // 重複を除外して追加
        const combined = [...new Set([...currentItems, ...newItems])];
        
        const newCategories = { ...prev.interests.categories };
        newCategories[selectedCategory] = { 
          ...newCategories[selectedCategory], 
          [field]: combined 
        };
        
        return { ...prev, interests: { ...prev.interests, categories: newCategories } };
      });

      await customAlert('AI Suggestions Added', `Gemini suggested ${newItems.length} new ${field} for "${selectedCategory}".`, 'success');
    } catch (err) {
      console.error(`Failed to get AI suggestions for ${field}:`, err);
      await customAlert('AI Suggestion Failed', `Could not reach Gemini to get suggestions for ${field}.`, 'error');
    } finally {
      if (field === 'brands') setIsSuggestingBrands(false);
      else setIsSuggestingKeywords(false);
    }
  };

  return (
    <div className="space-y-6">
      {/* Header & Main Actions */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <div className="p-2 bg-primary/20 rounded-lg text-primary">
              <Settings2 size={24} />
            </div>
            Nexus Command & Control
          </h1>
          <p className="text-sm text-slate-500 mt-1">Configure intelligence parameters, visualize knowledge, and manage agent skills.</p>
        </div>
        
        <div className="flex gap-3">
          {isDirty && (
            <motion.button
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              onClick={handleReset}
              data-testid="reset-draft-button"
              className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-400 hover:text-white transition-colors"
            >
              <RotateCcw size={16} />
              Reset Draft
            </motion.button>
          )}
          <button
            onClick={handleSave}
            disabled={!isDirty || isSaving || isSuggesting}
            data-testid="save-settings-button"
            className="flex items-center gap-2 px-6 py-2.5 text-sm font-bold bg-primary disabled:bg-slate-800 disabled:text-slate-600 text-white rounded-xl transition-all shadow-lg shadow-primary/20 hover:shadow-primary/40 active:scale-95"
          >
            <Save size={18} />
            {isSaving ? 'Synchronizing...' : isSuggesting ? 'Thinking...' : 'Save Configuration'}
          </button>
        </div>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-white/5 gap-8">
        <TabButton 
          active={activeTab === 'editor'} 
          onClick={() => setActiveTab('editor')} 
          icon={<Edit3 size={18} />} 
          label="Nexus Editor" 
          data-testid="tab-editor"
        />
        <TabButton 
          active={activeTab === 'graph'} 
          onClick={() => setActiveTab('graph')} 
          icon={<Network size={18} />} 
          label="Knowledge Graph" 
          data-testid="tab-graph"
        />
        <TabButton 
          active={activeTab === 'skills'} 
          onClick={() => setActiveTab('skills')} 
          icon={<Cpu size={18} />} 
          label="Skill Registry" 
          data-testid="tab-skills"
        />
      </div>

      {/* Tab Content */}
      <div className="min-h-[600px]">
        <AnimatePresence mode="wait">
          {activeTab === 'editor' && (
            <motion.div
              key="editor"
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="grid grid-cols-1 lg:grid-cols-12 gap-6"
            >
              {/* Category Sidebar */}
              <div className="lg:col-span-3 space-y-2">
                <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest px-2 mb-3">
                  Intelligence Categories
                </div>
                
                <Reorder.Group 
                  axis="y" 
                  values={categoryKeys} 
                  onReorder={handleReorderCategories}
                  className="space-y-2"
                >
                  {categoryKeys.map((catName) => (
                    <Reorder.Item 
                      key={catName} 
                      value={catName}
                      className="group relative flex items-center gap-1"
                    >
                      <div className="p-1 text-slate-700 cursor-grab active:cursor-grabbing opacity-0 group-hover:opacity-100 transition-opacity">
                        <GripVertical size={16} />
                      </div>
                      
                      <button
                        onClick={() => setSelectedCategory(catName)}
                        className={`flex-grow flex items-center gap-3 p-3 rounded-xl transition-all ${
                          selectedCategory === catName 
                            ? 'bg-primary/10 text-primary border border-primary/20 shadow-lg shadow-primary/5' 
                            : 'text-slate-400 hover:bg-white/5 border border-transparent'
                        }`}
                      >
                        <span className="text-xl">{draft.interests.categories[catName].emoji}</span>
                        <span className="font-semibold truncate text-left">{catName}</span>
                      </button>
                      
                      <div className="flex items-center opacity-0 group-hover:opacity-100 transition-opacity">
                        <button 
                          onClick={() => handleDeleteCategory(catName)}
                          className="p-2 text-slate-600 hover:text-alert transition-colors"
                          title="Delete Category"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </Reorder.Item>
                  ))}
                </Reorder.Group>

                <button 
                  onClick={handleAddCategory}
                  disabled={isSuggesting}
                  className="w-full flex items-center gap-3 p-3 text-slate-500 hover:text-accent hover:bg-accent/5 rounded-xl border border-dashed border-white/10 transition-all mt-4 disabled:opacity-50"
                >
                  <Plus size={18} />
                  <span className="text-sm font-medium">{isSuggesting ? 'Generating...' : 'Add New Category'}</span>
                </button>
              </div>

              {/* Editor Area */}
              <div className="lg:col-span-9 space-y-6">
                {selectedCategory && draft.interests.categories[selectedCategory] ? (
                  <>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                      {/* Brands Section */}
                      <GlassPanel className="p-6">
                        <div className="flex items-center justify-between mb-6">
                          <h3 className="font-bold flex items-center gap-2">
                            <Globe size={18} className="text-primary" />
                            Target Brands
                          </h3>
                          <div className="flex items-center gap-3">
                            <button
                              onClick={() => handleAISuggest('brands')}
                              disabled={isSuggestingBrands}
                              className="flex items-center gap-1.5 px-2 py-1 bg-primary/10 hover:bg-primary/20 text-primary rounded-md text-[10px] font-bold uppercase transition-all disabled:opacity-50"
                              title="AI Suggest Brands"
                            >
                              {isSuggestingBrands ? (
                                <RotateCcw size={12} className="animate-spin" />
                              ) : (
                                <Sparkles size={12} />
                              )}
                              AI Suggest
                            </button>
                            <span className="text-[10px] text-slate-500 font-mono">
                              {draft.interests.categories[selectedCategory].brands.length} Total
                            </span>
                          </div>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          {draft.interests.categories[selectedCategory].brands.map((brand, idx) => (
                            <div 
                              key={idx} 
                              className="group flex items-center gap-1.5 px-3 py-1.5 bg-primary/10 border border-primary/20 rounded-full text-sm text-primary-foreground animate-in fade-in zoom-in duration-200"
                            >
                              <span 
                                contentEditable
                                suppressContentEditableWarning
                                onBlur={(e) => {
                                  const newVal = e.currentTarget.textContent || '';
                                  const newBrands = [...draft.interests.categories[selectedCategory].brands];
                                  newBrands[idx] = newVal;
                                  handleUpdateCategory(selectedCategory, 'brands', newBrands.filter(b => b));
                                }}
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') {
                                    e.preventDefault();
                                    e.currentTarget.blur();
                                  }
                                }}
                                className="outline-none focus:text-white"
                              >
                                {brand}
                              </span>
                              <button 
                                onClick={() => {
                                  const newBrands = draft.interests.categories[selectedCategory].brands.filter((_, i) => i !== idx);
                                  handleUpdateCategory(selectedCategory, 'brands', newBrands);
                                }}
                                className="hover:text-alert transition-colors"
                              >
                                <X size={14} />
                              </button>
                            </div>
                          ))}
                          <button 
                            onClick={async () => {
                              const val = await customPrompt('Add Brand', 'Enter new brand name:');
                              if (val) {
                                const newBrands = [...draft.interests.categories[selectedCategory].brands, val];
                                handleUpdateCategory(selectedCategory, 'brands', newBrands);
                              }
                            }}
                            className="flex items-center justify-center w-8 h-8 rounded-full border border-dashed border-white/20 text-slate-500 hover:text-primary hover:border-primary/50 transition-all"
                            title="Add Brand"
                          >
                            <Plus size={16} />
                          </button>
                        </div>
                      </GlassPanel>

                      {/* Keywords Section */}
                      <GlassPanel className="p-6">
                        <div className="flex items-center justify-between mb-6">
                          <h3 className="font-bold flex items-center gap-2">
                            <Hash size={18} className="text-accent" />
                            Signal Keywords
                          </h3>
                          <div className="flex items-center gap-3">
                            <button
                              onClick={() => handleAISuggest('keywords')}
                              disabled={isSuggestingKeywords}
                              className="flex items-center gap-1.5 px-2 py-1 bg-accent/10 hover:bg-accent/20 text-accent rounded-md text-[10px] font-bold uppercase transition-all disabled:opacity-50"
                              title="AI Suggest Keywords"
                            >
                              {isSuggestingKeywords ? (
                                <RotateCcw size={12} className="animate-spin" />
                              ) : (
                                <Sparkles size={12} />
                              )}
                              AI Suggest
                            </button>
                            <span className="text-[10px] text-slate-500 font-mono">
                              {draft.interests.categories[selectedCategory].keywords.length} Total
                            </span>
                          </div>
                        </div>
                        <div className="flex flex-wrap gap-2">
                          {draft.interests.categories[selectedCategory].keywords.map((kw, idx) => (
                            <div 
                              key={idx} 
                              className="group flex items-center gap-1.5 px-3 py-1.5 bg-accent/10 border border-accent/20 rounded-full text-sm text-accent-foreground animate-in fade-in zoom-in duration-200"
                            >
                              <span 
                                contentEditable
                                suppressContentEditableWarning
                                onBlur={(e) => {
                                  const newVal = e.currentTarget.textContent || '';
                                  const newKws = [...draft.interests.categories[selectedCategory].keywords];
                                  newKws[idx] = newVal;
                                  handleUpdateCategory(selectedCategory, 'keywords', newKws.filter(k => k));
                                }}
                                onKeyDown={(e) => {
                                  if (e.key === 'Enter') {
                                    e.preventDefault();
                                    e.currentTarget.blur();
                                  }
                                }}
                                className="outline-none focus:text-white"
                              >
                                {kw}
                              </span>
                              <button 
                                onClick={() => {
                                  const newKws = [...draft.interests.categories[selectedCategory].keywords].filter((_, i) => i !== idx);
                                  handleUpdateCategory(selectedCategory, 'keywords', newKws);
                                }}
                                className="hover:text-alert transition-colors"
                              >
                                <X size={14} />
                              </button>
                            </div>
                          ))}
                          <button 
                            onClick={async () => {
                              const val = await customPrompt('Add Keyword', 'Enter new keyword:');
                              if (val) {
                                const newKws = [...draft.interests.categories[selectedCategory].keywords, val];
                                handleUpdateCategory(selectedCategory, 'keywords', newKws);
                              }
                            }}
                            className="flex items-center justify-center w-8 h-8 rounded-full border border-dashed border-white/20 text-slate-500 hover:text-accent hover:border-accent/50 transition-all"
                            title="Add Keyword"
                          >
                            <Plus size={16} />
                          </button>
                        </div>
                      </GlassPanel>
                    </div>

                    <div className="p-6 bg-primary/5 border border-primary/20 rounded-2xl">
                      <h4 className="text-xs font-bold text-primary uppercase tracking-widest mb-2">AI Reasoning Overlay</h4>
                      <p className="text-sm text-slate-400 italic">
                        "{draft.interests.categories[selectedCategory].reason || 'No specific reasoning provided for this category.'}"
                      </p>
                    </div>
                  </>
                ) : (
                  <div className="h-full flex items-center justify-center text-slate-600 border-2 border-dashed border-white/5 rounded-3xl">
                    Select a category to begin editing.
                  </div>
                )}
              </div>
            </motion.div>
          )}

          {activeTab === 'graph' && (
            <motion.div
              key="graph"
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.98 }}
            >
              <KnowledgeGraph 
                settings={draft} 
                onKeywordToggle={handleKeywordToggle}
                onBrandToggle={handleBrandToggle}
              />
            </motion.div>
          )}

          {activeTab === 'skills' && (
            <motion.div
              key="skills"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
            >
              <SkillRegistry 
                skills={draft.interests.skills} 
                onToggleSkill={handleToggleSkill} 
              />
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
};

interface TabButtonProps {
  active: boolean;
  onClick: () => void;
  icon: React.ReactNode;
  label: string;
  'data-testid'?: string;
}

const TabButton: React.FC<TabButtonProps> = ({ active, onClick, icon, label, 'data-testid': testId }) => (
  <button
    onClick={onClick}
    data-testid={testId}
    className={`flex items-center gap-2 py-4 border-b-2 transition-all font-semibold text-sm ${
      active 
        ? 'border-primary text-white' 
        : 'border-transparent text-slate-500 hover:text-slate-300'
    }`}
  >
    {icon}
    {label}
  </button>
);
